[package]
name = "kyu-delta"
version = "0.1.0"
edition = "2024"

[dependencies]
kyu-common = { path = "../kyu-common" }
kyu-types  = { path = "../kyu-types" }
smol_str   = { workspace = true }
hashbrown  = { workspace = true }
