[package]
name = "kyu-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
kyu-api     = { workspace = true }
kyu-catalog = { workspace = true }
kyu-common  = { workspace = true }
reedline    = { workspace = true }
