[package]
name = "ext-fts"
version = "0.1.0"
edition = "2024"

[dependencies]
kyu-extension = { workspace = true }
kyu-types     = { workspace = true }
smol_str      = { workspace = true }
tantivy       = { workspace = true }
